name: Update Telegram Countdown

on:
  schedule:
    - cron: "0 16 * * *" # 00:00 Asia/Taipei (UTC+8)
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Countdown Update
        env:
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          START_DATE: "2026-06-01"
          TARGET_DATE: "2026-07-08"
          END_DATE: "2026-07-08"
          TITLE_PREFIX: ${{ secrets.TELEGRAM_TITLE_PREFIX }}
        run: |
          chmod +x ./convert-and-upload.sh
          ./convert-and-upload.sh
